---
title: "Enheder"
author: "Lasse Hjorth Madsen"
published: "today"
format: html
---

## Hvad er enheder? {#sec-enheder}

Enheder er vigtige. For eksempel betyder det en del, om man kommer 20 *sekunder* for sent til en aftale, eller 20 *minutter* for sent. Sekunder og minutter er to forskellige tidsenheder. 

Enheder kan også være et uventet hjælpemiddel til at forstå, om vi har regnet rigtigt, eller hvordan et bestemt problem skal løses.

## Et løbeeksempel

Lad os sige, man løber 10 kilometer på 1 time. 10 er afstanden, *kilometer* afstandsenheden. 1 er tiden, *time* er tidsenheden.

Der er nogenlunde nemt at se, at den  *hastighed* man har løbet med, er 10 kilometer i timen, hvilket vi til daglig skriver sådan her: 10 km/t.

Regnestykket er så enkelt, at mange næsten ikke tænker over det, men vi har taget afstanden (de 10 kilometer) og divideret med tiden (den ene time) sådan her:

$$\frac{10\ km}{1\ t} = 10 \frac{km}{t}$$
Hvor kilometer er forkortet til $km$ og timer til $t$. Resultatet er den gennemsnitlige hastighed, og enheden er $\frac{km}{t}$, det samme som km/t, altså kilometer i timen. (Det er den *gennemsnitlige* hastighed, for man løber nok ikke præcist lige hurtigt hele vejen.) 

$\frac{km}{t}$ er altså *enheden* for hastighed. Det gode er, at enhederne opfører sig som ethvert andet regnestykke. Denne her lille udregning minder for eksempel meget om hastighedsudregningen før:

$$\frac{8\ a}{2\ b} = 4 \frac{a}{b}$$
Vi kan omskrive det lidt mere, hvis det er svært umiddelbart at se, hvorfor regnestykket er rigtigt:

$$\frac{8\ a}{2\ b} = \frac{8}{2} \cdot \frac{a}{b} = 4 \cdot \frac{a}{b} = 4\frac{a}{b}$$

Tricket er altså, at enheder opfører sig ligesom variablerne $a$ og $b$ i stykket herover.

Hvis vi i løbeeksemplet ikke ville udregne løbehastigheden målt i kilometer i timen, men i stedet for vide, hvor mange timer det tager at løbe en kilometer, ville regnestykket bare være den omvendte brøk:

$$\frac{1\ t}{10\ km} = 0,1 \frac{t}{km}$$
Det tager altså 0,1 time at løbe en kilometer, og enheden er nu $\frac{t}{km}$, timer per kilometer, ikke $\frac{km}{t}$. Løbere vil tit gerne vide, hvor mange *minutter*, ikke timer, det tager at løbe en kilometer. Og eftersom $60\ minutter = 1\ time$ kan vi bare stille omregningen sådan op:

$$0,1 \frac{t}{km} \cdot 60 \frac{min}{t} = 0,1 \cdot 60 \cdot \frac{t\cdot min}{km \cdot t} = 6 \frac{min}{km}$$
Det tager altså løberen 6 minutter ($min$) at løbe én kilometer.

Det kan godt være, at udregningen ser lidt forvirrende ud, så kig lidt på den og tænk over det. Det eneste vi har gjort, er at sige, at hvis det tager 0,1 time at løbe en kilometer, så tager det også 6 minutter at løbe en kilometer. Fordi 0,1 time er det samme som 6 minutter.   

Igen: Læg mærke til at vi fandt den nye enhed $\frac{min}{km}$ ved bare at behandle enhederne som almindelige tal eller variabler.

Hvis vi gerne vil ændre enhed igen, så se hvor lang tid det tager at løbe en meter ($m$), bruger vi blot at $1\ m = 0,001\ km$ og regner på samme måde:

$$6 \frac{min}{km} \cdot 0,001 \frac{km}{m} = 0,006 \frac{min}{m}$$

Det tager altså 0,006 minutter at løbe én meter.

Enheder kan hjælpe os her, fordi vi ved, at resultatet skal have enheden $\frac{min}{m}$, og vi kan kontrollere, at er den enhed vi får, når vi ganger de to tal -- og deres enheder -- sammen.


Hvis vil gerne vil have det i *sekunder* per meter, er det samme historie. Vi ved, at der 60 sekunder ($s$) per minut og skriver derfor: $0,006 \frac{min}{m} \cdot 60 \frac{s}{min} = 0,36 \frac{s}{m}$.

Det tager 0,36 sekunder at løbe en meter.

## Sjove enheder

### Frekvens

Hvis du fandt løbeeksemplet nemt, er det måske fordi enhederne, meter, minutter og sekunder er så velkendte.

En knap så kendt enhed er hertz, som bruges til at måle, hvor *ofte* noget forekommer i løbet at et bestemt tidsrum. Vi kalder det nogle gange frekvens.

Et eksempel kan være hjerteslag eller puls. Lad os sige, at en person har 90 hjerteslag på 60 sekunder. Pulsen er derfor:

$$ \frac{90}{60 s} = \frac{3}{2 s} = 1,5 \frac{1}{s} = 1,5 s^{-1}$$
Enheden for hertz er nemlig $s^{-1}$ og $s^{-1} = \frac{1}{s}$. (Hvis du tænker at det med en negativ potens er mærkeligt, så kig på afsnittet @sec-potenser)

Hertz kan godt virke forvirrende, fordi enheden $s^{-1}$ikke er så velkendt fra hverdagen. Grunden til at vi ender med en lidt sjov enhed er, at antallet af hjerteslag bare er almindelige tælletal. Tælleren i brøken $\frac{3}{2 s}$ har med andre ord ikke nogen enhed.

### Acceleration

Acceleration bruges til at beskrive hvor hurtig hastighed *ændrer* sig. En racerbil kommer for eksempel hurtigere op i fart end en lastbil; den har en højere *acceleration*.

[For sjov, kan vi lige regne ud, hvor mange $\frac{km}{t}$ det er: $$5\frac{m}{s} \cdot 0,001  \frac{km}{m} \cdot 3600 \frac{s}{t} = 18 \frac{km}{t} $$ Fordi en meter er 0,001 kilometer og fordi , der er $60 \cdot 60 = 3600$ sekunder på en time.]{.aside}

Lad os for eksempel sige, at en cykel kører 5 meter i sekundet, altså $5 \frac{m}{s}$.

Cyklisten beslutter sig for at overhale, og sætter farten op. 30 sekunder senere, kører cyklen $8 \frac{m}{s}$. På 30 sekunder har cyklisten altså øget sin hastighed med $3 \frac{m}{s}$. Hvor stor er hastighedsændringen per sekund -- det som vi kalder acceleration?

Vi kan regne det ud sådan her, og hvis vi husker enhederne, regner vi samtidig ud, hvad enheden for acceleration er:

$$\frac{3\frac{m}{s}}{30 s} =  \frac{1}{10} \frac{m}{s^2} = 0{,}1 \frac{m}{s^2}$$

Den udregning skal du måske lige tygge lidt på. Hvis det hjælper, kan vi bryde det ned i mindre skridt sådan her. Tag ét lighedstegn ad gangen og arbejd dig stille og roligt igennem udregningen.

$$\frac{3\frac{m}{s}}{30 s} = 3\frac{m}{s} \cdot \frac{1}{30s} = 3 \cdot \frac{1}{30} \cdot \frac{m}{s} \cdot \frac{1}{s} = \frac{1}{10} \frac{m}{s^2} = 0{,}1 \frac{m}{s^2}$$

Cyklen har altså øget sin hastighed med $0{,}1\frac{m}{s}$ *per sekund* og accelerationen er derfor $0{,}1 \frac{m}{s^2}$. *Enheden* for acceleration er med andre ord $\frac{m}{s^2}$. Det kan virke lidt mærkeligt, når man ser det første gang, men udregningen bekræfter, at det er sådan, det må være.

Selvom vi ikke på forhånd vidste, hvad enheden for acceleration var, kan vi altså finde ud af det, ved at tage enhederne (meter og sekunder) med i vores udregning.

Man bruger acceleration til mange ting. For eksempel er *tyngdeaccelerationen* omkring $9{,}8 \frac{m}{s^2}$. Det betyder, at hvis man smider en mønt ud fra toppen af et højt hus, så får tyngdekraften mønten til at falde 9,8 meter i sekundet *hurtigere* -- hvert sekund. Efter ét sekund falder mønten altså med $9{,}8 \frac{m}{s^2}$, efter to sekunder med $2 \cdot 9{,}8 \frac{m}{s^2} = 19{,}6 \frac{m}{s^2}$ og så videre, indtil den rammer jorden.   

Smart, ikke?

### Kraft

Kraft er en anden sjov størrelse, der måles i enheden newton som er $1\ kg\cdot\frac{m}{s^2}$

## Sammenfatning