---
title: "Kombinatorik"
author: "Lasse Hjorth Madsen"
published: "today"
format: html
---

```{r set_up}
library(tidyverse)
library(igraph)
```

## Hvad er kombinatorik?

Kombinatorik handler om, hvordan man kan vælge og sammensætte ting.

```{r}
#| fig-height: 5
#| fig-width: 11

par(mar = c(0, 0, 0, 0)) # No margin
g <- make_graph(edges = c(1, 2, 1, 3, 2, 4, 2, 5, 2, 6, 3, 7, 3, 8, 3, 9), n = 9, directed = FALSE)

angle <- 2 * pi * 0.75
rotation <- matrix(c(cos(angle), sin(angle), -sin(angle), cos(angle)), ncol = 2)
layout <- layout_as_tree(g, root = 1) %*% rotation

V(g)$color <- "lightblue"
V(g)$label <- c("Bukser", "T-shirt", "T-shirt", paste("Outfit", 6:1))
E(g)$label <- c("Blå", "Sort", "Grøn", "Gul", "Rød", "Grøn", "Gul", "Rød")

V(g)$frame.color <- NA
V(g)$size = 30
plot(g, layout = layout)
```


## Oversigt


|                     | Ordnet              | Uordnet             |
|---------------------|---------------------|---------------------|
| Med tilbagelægning  | Kombinationslås     | Bland-selv-slik     |
| Uden tilbagelægning | Holdopstilling      | Lotto-tal           |

: Fire typer af kombinationer {tbl-colwidths="[34,33,33]"}


|                     | Ordnet              | Uordnet
|---------------------|---------------------|---------------------|
| Med tilbagelægning  | $n^k$               | $\binom{n+k-1}{k} = \frac{(n+k-1)!}{k!(n-1)!}$  |
| Uden tilbagelægning | $\frac{n!}{(n-k)!}$ | $\binom{n}{k} = \frac{n!}{k!(n-k)!}$      |
: Formler for beregning af kombinationer {tbl-colwidths="[34,33,33]"}